### ISSUE TITLE
Nested media queries cause an error

### ISSUE THREAD

**Issue by raingerber** [raingerber/find-css-matches#4]
**Problem:**

An error is thrown for CSS like this:

```css
@media (max-width: 500px) {
  @media (orientation: portrait) {
    body {
      margin-top: 30px
    }
  }
}
```

`DOMException: Failed to execute 'webkitMatchesSelector' on 'Element': The provided selector is empty`

**Solution:**

Refactor `getCssRules` and `formatRule` to support nested media queries.
